default_agent: tigeragent
agents:
  tigeragent:
    name: tigeragent
    entrypoint: ./TigerAgent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: .
    aws:
      execution_role: arn:aws:iam::637423233204:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-b267b6c730
      execution_role_auto_create: false
      account: '637423233204'
      region: us-east-2
      ecr_repository: 637423233204.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-tigeragent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: tigeragent-euLdYk2j7o
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:637423233204:runtime/tigeragent-euLdYk2j7o
      agent_session_id: 2be43714-88c8-4b6d-b9e0-1521842488a6
    codebuild:
      project_name: bedrock-agentcore-tigeragent-builder
      execution_role: arn:aws:iam::637423233204:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-e3775f4bd8
      source_bucket: bedrock-agentcore-codebuild-sources-637423233204-us-east-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
